version: "3.8"

services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env.docker
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}
  app:
    build:
      context: ../
      dockerfile: ./producer/Dockerfile

    restart: always
    env_file:
      - ./.env.docker
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      ENVIRONMENT_NAME: "docker"
